trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g @cyclonedx/cyclonedx-npm
  displayName: 'npm install'

- script: |
    cyclonedx-npm --version
    cyclonedx-npm --output-file '$(Agent.TempDirectory)/bom.xml'
  displayName: 'Create BOM'
- task: upload-bom-dtrack-task@1
  inputs:
    bomFilePath: '/home/vsts/work/_temp/bom.xml'
    dtrackProjId: 'd8ab4234-2578-4290-b98c-43a7c5f8acdc'
    dtrackAPIKey: 'OQjOUA2lYlG144Rr6xf6yZ7lWrWLNKdl'
    dtrackURI: 'http://54.226.185.6:8080/'